### ISSUE TITLE
Input hmms file help

### ISSUE THREAD

**Issue by Ptero64** [JLSteenwyk/orthofisher#1]
Hello,

I will be very interested to test your software as an alternative to do reciprocal blast, to recover genes of interest from differents species genomic data to get multifasta of hopefully correct orthologs.

I havent used hmm before. How do we generate the hmm files for the argument -m? If we have a list of genes (gene name or Ensembl ID) can we use this info to fish out in the proteome?

Thanks for the help

regards

Nicolas

**Comment by JLSteenwyk** [comment]
Hi Nicolas,

Thank you for checking out orthofisher!

HMMs can be generated using HMMER3 http://hmmer.org/. More specifically, the function hmmbuild (http://www.csb.yale.edu/userguides/seq/hmmer/docs/node19.html) will construct an HMM from a multiple sequence alignment file. The resulting HMM (and other HMMs) can be pointed to in the -m argument.

Best,

Jacob L. Steenwyk
